### PR TITLE
Forward-port patch from Reiner Herrmann to make build reproducible

### PR DESCRIPTION
**Pull request by MatthewVernon**
This sets LOCALE for the changelog generation from html with lynx
--dump, and sorts the md5sums list.

The original of this was included in 3.x; this version does the equivalent for 4.x

### CODE REVIEW

**Comment by ewxrjk** [comment]
I don't see why this is needed given https://github.com/ewxrjk/rsbackup/blob/master/debian/rules#L26:

    # Debian apparently wants reproducible builds but won't execute them
    # in a consistent environment, so every project has to clean up after
    # it.
    export LC_ALL=C.UTF-8

**Comment by MatthewVernon** [comment]
Blast, missed that. Sorry for the noise!

**Comment by MatthewVernon** [comment]
...is md5sums reliably sorted without the `sort` ?

**Comment by ewxrjk** [comment]
No, it won't be. I'll accept a PR that adds just the `sort`.

**Comment by MatthewVernon** [comment]
Here you are :)

**Comment by MatthewVernon** [comment]
[i.e. I think this is now a single-commit PR to just add the `sort`]

**Pull request closed without merging**
